version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: ducks-backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@ducks-db/ducks_db    
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: ducks
    depends_on:
      - db
      - minio
    
  frontend:
    build: ./frontend
    container_name: ducks-frontend
    ports:
      - "3000:3000" # Expose React app on port 3000
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: ducks-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ducks_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: ducks-minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001" # For MinIO Console
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data:
